# SPDX-FileCopyrightText: Copyright (c) 2026
# SPDX-License-Identifier: Apache-2.0
"""A minimal, from-scratch Projected Gauss--Seidel solver for Newton.

``SolverPGS`` is deliberately a reference implementation rather than a
production backend.  It solves only unilateral rigid-body contacts and uses a
single Warp thread to visit contact rows in a fixed order.  This makes the
algorithm transparent and mathematically faithful to velocity-level PGS:

    v* = v_n + dt M^-1 f_ext
    lambda_i <- project(lambda_i + delta_lambda_i)
    v* <- v* + M^-1 J_i^T delta_lambda_i
    q_{n+1} <- integrate(q_n, v*)

Supported:
    * dynamic and kinematic rigid bodies;
    * unilateral normal contacts;
    * optional Coulomb friction-disk projection;
    * gravity and ``State.body_f`` external wrenches.

Intentionally excluded from this first solver:
    * particles, soft bodies, joints, actuators, restitution and CCD;
    * warm starting between time steps;
    * differentiable simulation;
    * performance-oriented contact coloring or batching.
"""

from __future__ import annotations

import warp as wp

from ...core.types import override
from ...sim import Contacts, Control, Model, ModelFlags, State
from ..solver import SolverBase
from .kernels import integrate_body_positions, predict_body_velocities, solve_contacts_pgs

__all__ = ["SolverPGS"]


class SolverPGS(SolverBase):
    """Educational velocity-level Projected Gauss--Seidel contact solver.

    The solver expects rigid contacts to have been generated by Newton's normal
    collision pipeline and supplied to :meth:`step`.  It does not generate
    contacts itself.

    Args:
        model: Newton model containing only rigid, joint-free bodies.
        iterations: Number of complete sequential PGS sweeps per time step.
        baumgarte: Fraction of penetration corrected as target separating
            velocity on every time step.  ``0`` gives a purely velocity-level
            contact solve; values around ``0.1``--``0.3`` are a reasonable
            teaching/demo range.
        contact_slop: Penetration tolerated before Baumgarte correction starts.
        max_bias_velocity: Upper bound for positional-bias separating speed.
        enable_friction: Apply a Coulomb friction-disk projection after each
            normal constraint update.
        angular_damping: Simple non-negative angular velocity damping rate.

    The contact sweep is intentionally one-threaded, so this solver is useful
    for understanding and validating PGS but not for large simulations.
    """

    def __init__(
        self,
        model: Model,
        *,
        iterations: int = 10,
        baumgarte: float = 0.2,
        contact_slop: float = 1.0e-3,
        max_bias_velocity: float = 2.0,
        enable_friction: bool = True,
        angular_damping: float = 0.0,
    ):
        super().__init__(model=model)

        if model.particle_count:
            raise NotImplementedError("SolverPGS v1 supports rigid bodies only; particles are not supported.")
        if model.joint_count:
            raise NotImplementedError("SolverPGS v1 does not yet implement joint constraint rows.")
        if iterations <= 0:
            raise ValueError("iterations must be positive")
        if not 0.0 <= baumgarte <= 1.0:
            raise ValueError("baumgarte must be in the inclusive range [0, 1]")
        if contact_slop < 0.0:
            raise ValueError("contact_slop must be non-negative")
        if max_bias_velocity < 0.0:
            raise ValueError("max_bias_velocity must be non-negative")
        if angular_damping < 0.0:
            raise ValueError("angular_damping must be non-negative")

        self.iterations = iterations
        self.baumgarte = float(baumgarte)
        self.contact_slop = float(contact_slop)
        self.max_bias_velocity = float(max_bias_velocity)
        self.enable_friction = bool(enable_friction)
        self.angular_damping = float(angular_damping)

        # SolverBase builds these copies with zero inverse mass/inertia for
        # kinematic bodies.  The PGS contact kernel uses them as infinite-mass
        # bodies while preserving their user-authored motion.
        self._init_kinematic_state()

    @override
    def notify_model_changed(self, flags: ModelFlags | int) -> None:
        """Refresh the effective mass data after a body edit."""
        if flags & (ModelFlags.BODY_PROPERTIES | ModelFlags.BODY_INERTIAL_PROPERTIES):
            self._refresh_kinematic_state()

    @override
    def step(
        self,
        state_in: State,
        state_out: State,
        control: Control | None,
        contacts: Contacts | None,
        dt: float,
    ) -> None:
        """Advance one time step using velocity-level PGS contact impulses.

        ``control`` is accepted to match :class:`SolverBase`, but deliberately
        unused because this first implementation has no joint/actuator rows.
        """
        del control

        if dt <= 0.0:
            raise ValueError("dt must be positive")
        if state_in.requires_grad:
            raise NotImplementedError("SolverPGS v1 is a non-differentiable reference solver.")

        model = self.model
        if model.body_count == 0:
            return

        # 1. Form the unconstrained velocity v* from external force and gravity.
        wp.launch(
            kernel=predict_body_velocities,
            dim=model.body_count,
            inputs=[
                state_in.body_q,
                state_in.body_qd,
                state_in.body_f,
                model.body_com,
                model.body_inertia,
                model.body_inv_mass,
                model.body_inv_inertia,
                model.body_flags,
                model.body_world,
                model.gravity,
                self.angular_damping,
                dt,
            ],
            outputs=[state_out.body_qd],
            device=model.device,
        )

        # Per-step accumulated impulses.  Keeping them only for this time step
        # makes the relationship between the PGS equation and the code explicit;
        # cross-step warm starting can be added later as a separate experiment.
        if contacts is not None and contacts.rigid_contact_max > 0:
            normal_lambda = wp.zeros(contacts.rigid_contact_max, dtype=float, device=model.device)
            tangent_lambda = wp.zeros(contacts.rigid_contact_max, dtype=wp.vec3, device=model.device)

            # 2. Each launch performs exactly one contact-order PGS sweep.
            for _ in range(self.iterations):
                wp.launch(
                    kernel=solve_contacts_pgs,
                    dim=1,
                    inputs=[
                        state_in.body_q,
                        state_out.body_qd,
                        model.body_com,
                        self.body_inv_mass_effective,
                        self.body_inv_inertia_effective,
                        model.shape_body,
                        model.shape_material_mu,
                        contacts.rigid_contact_count,
                        contacts.rigid_contact_shape0,
                        contacts.rigid_contact_shape1,
                        contacts.rigid_contact_point0,
                        contacts.rigid_contact_point1,
                        contacts.rigid_contact_normal,
                        contacts.rigid_contact_margin0,
                        contacts.rigid_contact_margin1,
                        contacts.rigid_contact_max,
                        self.baumgarte,
                        self.contact_slop,
                        self.max_bias_velocity,
                        dt,
                        self.enable_friction,
                    ],
                    # ``state_out.body_qd`` is deliberately an in-place
                    # read/write kernel argument above.  The lambda buffers
                    # occupy the final two kernel parameters.
                    outputs=[normal_lambda, tangent_lambda],
                    device=model.device,
                )

        # 3. Advance the pose once, using the PGS-corrected velocity.
        wp.launch(
            kernel=integrate_body_positions,
            dim=model.body_count,
            inputs=[state_in.body_q, state_out.body_qd, model.body_com, model.body_flags, dt],
            outputs=[state_out.body_q],
            device=model.device,
        )

        # This solver has no joints, so the optional incoming-joint wrench is
        # exactly zero when a caller requested that extended state field.
        if state_out.body_parent_f is not None:
            state_out.body_parent_f.zero_()
